use_frameworks!

target 'akupriia2019_Example' do
  pod 'akupriia2019', :path => '../'

  target 'akupriia2019_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
